#-----------mybatisPlus配置-----------------------------------------
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted #逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)